# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b075ea2ed1e78a801582bd0b30977ab384115f40b3e840787d20d368cb3921a730154619ead9cc42f1dc9b47e743c28fca8132fde5ebb9ad99497e21c0e6772

test:
  secret_key_base: 62dd6796e7e0a3de2d286e2bea21001a865211956bf42625f763c00085aea4b16ae7c2ac29e580c702ee335a032ec7852802657bf11cba1aa4cf9abbf53e9bc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
